wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1714976493.287662
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.13.4
      8:
      - 1
      - 5
    visualize:
      curves/F1-Confidence(B):
        panel_config:
          fieldSettings:
            class: class
            x: x
            y: y
          panelDefId: wandb/area-under-curve/v0
          stringSettings:
            title: F1-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: F1
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: curves/F1-Confidence(B)_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      curves/Precision-Confidence(B):
        panel_config:
          fieldSettings:
            class: class
            x: x
            y: y
          panelDefId: wandb/area-under-curve/v0
          stringSettings:
            title: Precision-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: Precision
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: curves/Precision-Confidence(B)_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      curves/Precision-Recall(B):
        panel_config:
          fieldSettings:
            class: class
            x: x
            y: y
          panelDefId: wandb/area-under-curve/v0
          stringSettings:
            title: Precision-Recall(B)
            x-axis-title: Recall
            y-axis-title: Precision
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: curves/Precision-Recall(B)_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      curves/Recall-Confidence(B):
        panel_config:
          fieldSettings:
            class: class
            x: x
            y: y
          panelDefId: wandb/area-under-curve/v0
          stringSettings:
            title: Recall-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: curves/Recall-Confidence(B)_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
agnostic_nms:
  desc: null
  value: false
amp:
  desc: null
  value: true
augment:
  desc: null
  value: false
auto_augment:
  desc: null
  value: randaugment
batch:
  desc: null
  value: 32
bgr:
  desc: null
  value: 0.0
box:
  desc: null
  value: 7.5
cache:
  desc: null
  value: true
cfg:
  desc: null
  value: null
classes:
  desc: null
  value: null
close_mosaic:
  desc: null
  value: 10
cls:
  desc: null
  value: 0.5
conf:
  desc: null
  value: null
copy_paste:
  desc: null
  value: 0.0
cos_lr:
  desc: null
  value: false
crop_fraction:
  desc: null
  value: 1.0
data:
  desc: null
  value: /notebooks/thesis-train/datasets/filipino-fridge-items-14/data.yaml
degrees:
  desc: null
  value: 0.0
deterministic:
  desc: null
  value: true
device:
  desc: null
  value: null
dfl:
  desc: null
  value: 1.5
dnn:
  desc: null
  value: false
dropout:
  desc: null
  value: 0.0
dynamic:
  desc: null
  value: false
embed:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
erasing:
  desc: null
  value: 0.4
exist_ok:
  desc: null
  value: false
fliplr:
  desc: null
  value: 0.5
flipud:
  desc: null
  value: 0.0
format:
  desc: null
  value: torchscript
fraction:
  desc: null
  value: 1.0
freeze:
  desc: null
  value: null
half:
  desc: null
  value: false
hsv_h:
  desc: null
  value: 0.015
hsv_s:
  desc: null
  value: 0.7
hsv_v:
  desc: null
  value: 0.4
imgsz:
  desc: null
  value: 640
int8:
  desc: null
  value: false
iou:
  desc: null
  value: 0.7
keras:
  desc: null
  value: false
kobj:
  desc: null
  value: 1.0
label_smoothing:
  desc: null
  value: 0.0
line_width:
  desc: null
  value: null
lr0:
  desc: null
  value: 0.01
lrf:
  desc: null
  value: 0.01
mask_ratio:
  desc: null
  value: 4
max_det:
  desc: null
  value: 300
mixup:
  desc: null
  value: 0.0
mode:
  desc: null
  value: train
model:
  desc: null
  value: yolov8n.pt
momentum:
  desc: null
  value: 0.937
mosaic:
  desc: null
  value: 1.0
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: train4
nbs:
  desc: null
  value: 64
nms:
  desc: null
  value: false
opset:
  desc: null
  value: null
optimize:
  desc: null
  value: false
optimizer:
  desc: null
  value: auto
overlap_mask:
  desc: null
  value: true
patience:
  desc: null
  value: 100
perspective:
  desc: null
  value: 0.0
plots:
  desc: null
  value: true
pose:
  desc: null
  value: 12.0
pretrained:
  desc: null
  value: true
profile:
  desc: null
  value: false
project:
  desc: null
  value: null
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
retina_masks:
  desc: null
  value: false
save:
  desc: null
  value: true
save_conf:
  desc: null
  value: false
save_crop:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/detect/train4
save_frames:
  desc: null
  value: false
save_hybrid:
  desc: null
  value: false
save_json:
  desc: null
  value: false
save_period:
  desc: null
  value: -1
save_txt:
  desc: null
  value: false
scale:
  desc: null
  value: 0.5
seed:
  desc: null
  value: 0
shear:
  desc: null
  value: 0.0
show:
  desc: null
  value: false
show_boxes:
  desc: null
  value: true
show_conf:
  desc: null
  value: true
show_labels:
  desc: null
  value: true
simplify:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
source:
  desc: null
  value: null
split:
  desc: null
  value: val
stream_buffer:
  desc: null
  value: false
task:
  desc: null
  value: detect
time:
  desc: null
  value: null
tracker:
  desc: null
  value: botsort.yaml
translate:
  desc: null
  value: 0.1
val:
  desc: null
  value: true
verbose:
  desc: null
  value: true
vid_stride:
  desc: null
  value: 1
visualize:
  desc: null
  value: false
warmup_bias_lr:
  desc: null
  value: 0.1
warmup_epochs:
  desc: null
  value: 3.0
warmup_momentum:
  desc: null
  value: 0.8
weight_decay:
  desc: null
  value: 0.0005
workers:
  desc: null
  value: 8
workspace:
  desc: null
  value: 4
